get batch data by number api
0xPolygon/cdk-erigon pull request #1090
Opened 2024-09-03 08:38 UTC by ARR552

This PR adds a modification in GetBatchDataByNumbers endpoint to avoid calculate batchData when it is stored in db

2024-09-04 07:00 UTC, revitteth approved these changes

2024-09-04 08:03 UTC, revitteth commented
Looks like this breaks kurtosis - please investigate!

2024-09-04 12:22 UTC, mandrigin requested changes
Small stuff

2024-09-04 12:22 UTC, mandrigin commented on cmd/rpcdaemon/commands/zkevm_api.go
> +		batchData, err := hermezDb.GetL1BatchData(batchNumber.Uint64())
We probably should extract the rest as “GenerateL1BatchData” to have the whole structure more clear. Otherwise it’s okay.

2024-09-26 09:32 UTC, V-Staykov commented
This is already done, closing.

2024-09-26 09:32 UTC, closed without merging