1298 acl access control list augmentation
0xPolygon/cdk-erigon pull request #1303
Opened 2024-10-10 00:06 UTC by afa7789

2024-10-11 20:50 UTC, afa7789 commented
<img width="622" alt="image" src="https://github.com/user-attachments/assets/2a66eab4-54c1-4a93-81fb-e405c6036060">
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/1a8004e7-0e2c-4a5f-93b2-4f4a67ea70c6">

2024-10-14 10:09 UTC, hexoscott requested changes
Changes look good, but we need to address the logging thing before we can merge

2024-10-14 10:09 UTC, hexoscott commented on cmd/acl/main.go
> -	logging.LogConsoleVerbosityFlag.Value = log.LvlError.String()
could removing these lines be the reason log/v3 isn't working as expected?

2024-10-16 10:11 UTC, hexoscott commented
Hi @afa7789 - are we considering this good to review again?  Did adding the log level stuff back in help with the v3 logging library problem you were seeing?

2024-10-18 12:33 UTC, revitteth approved these changes, later dismissed

2024-10-18 12:46 UTC, hexoscott approved these changes, later dismissed

2024-10-18 14:53 UTC, hexoscott approved these changes

2024-10-18 15:48 UTC, merged