support zero gas price transactions
0xPolygon/cdk-erigon pull request #305
Opened 2024-04-17 16:03 UTC by hexoscott

I tried to make the changes permeate less through the codebase but struggled.  We want to be able to control this with a flag and likely after genesis so we can't rely on the chain config stored in the DB against the genesis hash for this so ended up passing a boolean to the base api instead for RPC calls.  The CalcBaseFee uses a chain config passed from app startup so that was easier to handle.

2024-04-17 16:16 UTC, mandrigin commented on chain/chain_config.go
> +	SupportZeroGas bool `json:"supportZeroGas,omitempty"`
I was wondering for a while, what if we have ZkConfig with all these fields and then just combine it as an anonymous field to Config?

like 

```
type ZkConfig struct {
     ForkID4Block ...
     ...
}

type Config struct {
      ZkConfig
      ....
 }
 ```
 
 
 will be an easier rebase

2024-04-17 16:17 UTC, mandrigin commented on consensus/misc/eip1559.go
> +	if config.SupportZeroGas {
maybe CalcBaseFeeZk somehow and then move to _zkevm?

2024-04-17 16:17 UTC, mandrigin requested changes
a few comments that are not necessary, but I want to hear back your opinion @hexoscott

2024-04-17 16:20 UTC, mandrigin commented on cmd/rpcdaemon/commands/eth_api.go
> +func NewBaseApi(f *rpchelper.Filters, stateCache kvcache.Cache, blockReader services.FullBlockReader, agg *libstate.AggregatorV3, singleNodeMode bool, evmCallTimeout time.Duration, engine consensus.E
I am beginning to wonder if we should actually change the constructor here and instead have a method "SetGasless()" that will be initialized later.

Or have NewZkBaseApi with the extra param.

2024-04-18 06:57 UTC, hexoscott commented
Agreed on all of the above, thanks for the review.  I'll see what merging the configs looks like, that might be a larger task than I can get into this PR so may want to tackle it separately.

2024-04-18 08:27 UTC, hexoscott commented
OK PR is good to review again.  Tidied it up a lot now and renamed from zerogas to gasless.  I'll pick up the config merging in another PR as it would get noisy to do it here.

2024-04-18 12:35 UTC, mandrigin approved these changes
nice! much less changes too

2024-04-18 12:35 UTC, merged