Add Normalcy fork
0xPolygon/cdk-erigon pull request #676
Opened 2024-06-27 21:06 UTC by cffls

Add Normalcy hardfork, which allows a chain to follow standard EVM in core execution, excluding pre/post-execution. Design rationale could be seen in this [doc](https://hackmd.io/4LplWzQkTQyQr0_SUrJCMQ).

2024-06-27 21:25 UTC, revitteth approved these changes
I can't access the doc but the changes look ok to me :)

2024-06-27 21:30 UTC, cffls commented
> I can't access the doc but the changes look ok to me :)
Thanks for the quick response! I just opened the doc to public. You can try again now :D

2024-06-28 05:43 UTC, Stefan-Ethernal approved these changes

2024-06-28 05:43 UTC, Stefan-Ethernal commented on erigon-lib/chain/chain_config.go
> +	return fmt.Sprintf("{ChainID: %v, Homestead: %v, DAO: %v, Tangerine Whistle: %v, Spurious Dragon: %v, Byzantium: %v, Constantinople: %v, Petersburg: %v, Istanbul: %v, Muir Glacier: %v, Berlin: %v, L
Optional nitpick: consider using `%t` to format all the boolean values in the string.

2024-06-28 07:26 UTC, mandrigin requested changes
some questions about abstractions

2024-07-01 08:56 UTC, mandrigin approved these changes

2024-07-01 08:56 UTC, merged

2024-07-01 18:55 UTC, Sharonbc01 commented
Hey @mandrigin just checking as Jerry is out this week. Were you okay with his proposed changes and his write up on the Normalcy fork>  https://hackmd.io/@4cbvqzFdRBSWMHNeI8Wbwg/r1hKHp_S0